=== twosixlabs/armory/armory/utils/config_schema.json
{
    "$id": "https://twosixlabs.com/armory/config_schema#",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "adhoc": {
            "type": "object"
        },
        "attack": {
            "properties": {
                "budget": {
                    "$comment": "What should this object look like?",
                    "type": [
                        "object",
                        "null"
                    ]
                },
                "knowledge": {
                    "$comment": "What other values are valid?",
                    "enum": [
                        "white",
                        "black"
                    ],
                    "type": "string"
                },
                "kwargs": {
                    "type": "object"
                },
                "module": {
                    "$ref": "#/definitions/python_module"
                },
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "module",
                "name",
                "kwargs",
                "knowledge",
                "budget"
            ],
            "type": "object"
        },
        "dataset": {
            "properties": {
                "batch_size": {
                    "minimum": 1,
                    "type": "integer"
                },
                "module": {
                    "$ref": "#/definitions/python_module"
                },
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "batch_size",
                "module",
                "name"
            ],
            "type": "object"
        },
        "defense": {
            "properties": {
                "kwargs": {
                    "type": "object"
                },
                "module": {
                    "$ref": "#/definitions/python_module"
                },
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "module",
                "name",
                "kwargs"
            ],
            "type": "object"
        },
        "evaluation": {
            "properties": {
                "eval_file": {
                    "type": "string"
                }
            },
            "required": [
                "eval_file"
            ],
            "type": "object"
        },
        "metric": {
            "properties": {
                "kwargs": {
                    "type": "object"
                },
                "module": {
                    "$ref": "#/definitions/python_module"
                },
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "module",
                "name",
                "kwargs"
            ],
            "type": "object"
        },
        "model": {
            "properties": {
                "model_kwargs": {
                    "type": "object"
                },
                "module": {
                    "$ref": "#/definitions/python_module"
                },
                "name": {
                    "type": "string"
                },
                "weights_file": {
                    "$comment": "Is this field optional?",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "wrapper_kwargs": {
                    "type": "object"
                }
            },
            "required": [
                "module",
                "name",
                "model_kwargs",
                "weights_file",
                "wrapper_kwargs"
            ],
            "type": "object"
        },
        "python_module": {
            "$comment": "Validate that it looks like a Python module path",
            "pattern": "^([a-zA-Z0-9_\\-]+\\.)*[a-zA-Z0-9_-]+$",
            "type": "string"
        },
        "sysconfig": {
            "properties": {
                "docker_image": {
                    "type": "string"
                },
                "external_github_repo": {
                    "$comment": "Can this be absent/null?",
                    "type": "string"
                },
                "use_gpu": {
                    "type": "boolean"
                }
            },
            "required": [
                "docker_image",
                "external_github_repo",
                "use_gpu"
            ],
            "type": "object"
        }
    },
    "properties": {
        "adhoc": {
            "anyOf": [
                {
                    "$ref": "#/definitions/adhoc"
                },
                {
                    "type": "null"
                }
            ]
        },
        "attack": {
            "anyOf": [
                {
                    "$ref": "#/definitions/attack"
                },
                {
                    "type": "null"
                }
            ]
        },
        "dataset": {
            "anyOf": [
                {
                    "$ref": "#/definitions/dataset"
                },
                {
                    "type": "null"
                }
            ]
        },
        "defense": {
            "anyOf": [
                {
                    "$ref": "#/definitions/defense"
                },
                {
                    "type": "null"
                }
            ]
        },
        "evaluation": {
            "$ref": "#/definitions/evaluation"
        },
        "metric": {
            "anyOf": [
                {
                    "$ref": "#/definitions/metric"
                },
                {
                    "type": "null"
                }
            ]
        },
        "model": {
            "anyOf": [
                {
                    "$ref": "#/definitions/model"
                },
                {
                    "type": "null"
                }
            ]
        },
        "sysconfig": {
            "$ref": "#/definitions/sysconfig"
        }
    },
    "title": "Schema for Armory evaluation configuration JSON files",
    "type": "object"
}

=== twosixlabs/armory/tests/test_data/fgm_attack_test.json
{
    "adhoc": {
        "batch_size": 64,
        "epochs": 3
    },
    "attack": {
        "budget": null,
        "knowledge": "white",
        "kwargs": {
            "eps": 0.2
        },
        "module": "art.attacks",
        "name": "FastGradientMethod"
    },
    "dataset": {
        "module": "armory.data.datasets",
        "name": "mnist"
    },
    "defense": null,
    "evaluation": {
        "eval_file": "armory-example.evaluations.fgm_attack"
    },
    "metric": null,
    "model": {
        "model_kwargs": {},
        "module": "armory.baseline_models.keras.keras_mnist",
        "name": "get_art_model",
        "wrapper_kwargs": {
            "clip_values": [
                0,
                1
            ]
        }
    },
    "sysconfig": {
        "docker_image": "twosixarmory/tf1:0.5.0",
        "external_github_repo": "twosixlabs/armory-example",
        "use_gpu": false
    }
}

=== twosixlabs/armory/armory/scenarios/configs/ucf101_baseline_pretrained.json
{
    "adhoc": {
        "train_epochs": 10
    },
    "attack": {
        "budget": null,
        "knowledge": "white",
        "kwargs": {
            "eps": 51.0
        },
        "module": "art.attacks",
        "name": "FastGradientMethod"
    },
    "dataset": {
        "batch_size": 16,
        "module": "armory.data.datasets",
        "name": "ucf101"
    },
    "defense": null,
    "evaluation": {
        "eval_file": "armory.scenarios.ucf101_scenario"
    },
    "metric": null,
    "model": {
        "model_kwargs": {
            "model_status": "ucf101_trained"
        },
        "module": "armory.baseline_models.pytorch.ucf101_mars",
        "name": "get_art_model",
        "weights_file": "MARS_UCF101_16f.pth",
        "wrapper_kwargs": {}
    },
    "sysconfig": {
        "docker_image": "twosixarmory/pytorch:0.6.0-dev",
        "external_github_repo": "davidslater/MARS",
        "use_gpu": false
    }
}

=== twosixlabs/armory/tests/configs/fgm_attack_test.json
{
    "adhoc": {
        "train_epochs": 3
    },
    "attack": {
        "budget": null,
        "knowledge": "white",
        "kwargs": {
            "eps": 0.2
        },
        "module": "art.attacks",
        "name": "FastGradientMethod"
    },
    "dataset": {
        "batch_size": 64,
        "module": "armory.data.datasets",
        "name": "mnist"
    },
    "defense": null,
    "evaluation": {
        "eval_file": "tests.evals.fgm_attack"
    },
    "metric": null,
    "model": {
        "model_kwargs": {},
        "module": "armory.baseline_models.keras.mnist",
        "name": "get_art_model",
        "weights_file": null,
        "wrapper_kwargs": {}
    },
    "sysconfig": {
        "docker_image": "twosixarmory/tf1:0.6.0-dev",
        "external_github_repo": "twosixlabs/armory-example",
        "use_gpu": false
    }
}

=== twosixlabs/armory/armory/scenarios/configs/sincnet.json
{
    "adhoc": {
        "epochs": 20000,
        "num_classes": 40
    },
    "attack": {
        "budget": {
            "norm": [
                "L2"
            ]
        },
        "knowledge": "white",
        "kwargs": {
            "eps": 0.2
        },
        "module": "art.attacks",
        "name": "FastGradientMethod"
    },
    "dataset": {
        "batch_size": 128,
        "module": "armory.data.datasets",
        "name": "librispeech_dev_clean"
    },
    "defense": null,
    "evaluation": {
        "eval_file": "armory.scenarios.raw_audio_scenario"
    },
    "metric": null,
    "model": {
        "model_kwargs": {
            "model_file": "model_sincnet.pth",
            "pretrained": true
        },
        "module": "armory.baseline_models.pytorch.sincnet",
        "name": "get_art_model",
        "wrapper_kwargs": {}
    },
    "sysconfig": {
        "docker_image": "twosixarmory/pytorch:0.6.0-dev",
        "external_github_repo": "davidslater/SincNet",
        "use_gpu": false
    }
}

=== twosixlabs/armory/tests/configs/sincnet.json
{
    "adhoc": {
        "epochs": 120,
        "num_attacked_pts": 100,
        "num_classes": 40,
        "seed": 123
    },
    "attack": {
        "budget": {
            "norm": [
                "L2"
            ]
        },
        "knowledge": "white",
        "kwargs": {
            "targeted": false
        },
        "module": "art.attacks",
        "name": "ProjectedGradientDescent"
    },
    "dataset": {
        "module": "armory.data.datasets",
        "name": "librispeech_dev_clean",
        "batch_size": 16
    },
    "defense": null,
    "evaluation": {
        "eval_file": "tests.evals.raw_audio_scenario"
    },
    "metric": null,
    "model": {
        "model_kwargs": {
            "pretrained": true,
            "model_file": "model_sincnet.pkl"
        },
        "module": "armory.baseline_models.pytorch.sincnet",
        "name": "get_art_model",
        "wrapper_kwargs": {}
    },
    "sysconfig": {
        "docker_image": "twosixarmory/pytorch:0.6.0-dev",
        "external_github_repo": "hkakitani/SincNet",
        "use_gpu": true
    }
}
